#!/bin/sh -
#
# $Id: zfssnap,v 1.6 2012/02/10 08:23:50 e52202 Exp $
#
############################################################################
#
# zfssnap
#
# Usage: zfssnap -s snapname [-n maxsnaps] filesystem
#
# This script takes a snapshot of a ZFS filesystem and all its child
# filesystems.  If a value is specified for "-t" it will also remove the
# oldest snapshots until there are "t" snapshots left (oldest to newest.)
#
# Suggested values for "t": 25 (hourly), 8 (daily), 5 (weekly), 13 (monthly)
#
# CURRENTLY UNTESTED ON SOLARIS.
#
# Author: Adrian Waters <awaters@draenan.net>
#
############################################################################

IFS=' 	
'
PATH=/bin:/usr/bin

progname=${0##*/}

usage () {
    echo "Usage: $progname -s snapname [-n maxsnaps] filesystem" >&2
    exit 1
}


case $(/usr/bin/uname -s) in
    FreeBSD)
        ID=/usr/bin/id
        GREP=/usr/bin/grep
        ZFS=/sbin/zfs
        DATE=/bin/date
        AWK=/usr/bin/awk
        ;;
    SunOS)
        ID=/usr/xpg4/bin/id
        GREP=/usr/xpg4/bin/grep
        ZFS=/sbin/zfs
        DATE=/usr/bin/date
        AWK=/usr/xpg4/bin/awk
        ;;
    *)
        echo "$progname: FreeBSD or Solaris only." >&2
        exit 1
        ;;
esac        

if [ "$#" -lt 3 ]; then
    usage
fi    

if [ $($ID -u) -ne "0" ]; then
    echo "You need to be root." >&2
    exit 1
fi    

pool_fs= pool= fs= snapname= maxsnaps=

while getopts :s:n: opt; do
    case $opt in
        s)
            snapname=$OPTARG
            ;;
        n)
            maxsnaps=$OPTARG
            ;;
        '?')
            usage
            ;;
    esac        
done

shift $((OPTIND - 1))

if [ -z "$1" ]; then
	usage
fi

pool_fs=$1
pool=${pool_fs%%/*}
fs=${pool_fs#*/}
if [ "X$fs" == "X$pool" ]; then
	fs=
fi	

echo $pool_fs | $GREP -E '^/|/$'
if [ "$?" -eq "0" ]; then
	echo "$progname: Cannot create snapshot: leading or trailing slash in \"$pool_fs\"." >&2
	exit 1
fi

if [ -z "$pool" ]; then
	echo "$progname: Cannot create snapshot: leading slash in \"$pool_fs\"." >&2
	exit 1
fi	

echo $pool | $GREP -E '^(c[0-9].*|mirror|raidz|spare|log)$|[^-_.[:alnum:]]' > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
    echo "$progname: \"$pool\" is not a valid ZFS pool name." >&2
    exit 1
fi    

if [ ! -z "$fs" ]; then
    echo $fs | $GREP -E '[^-_/.:[:alnum:]]' > /dev/null 2>&1
    if [ "$?" -eq "0" ]; then
        echo "$progname: \"$pool_fs\" is not a valid ZFS filesystem name." >&2
        exit 1
    fi
fi

$ZFS list -H -o name $pool_fs > /dev/null 2>&1

if [ "$?" -ne "0" ]; then
    echo "$progname: ZFS filesystem \"$pool_fs\" does not exist." >&2
    exit 1
fi    

echo $snapname | $GREP -E '[^-_.:[:alnum:]]' > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
    echo "$progname: \"$snapname\" is not a valid ZFS snapshot name." >&2
    exit 1
fi    

if [ ! -z "$maxsnaps" ]; then
    echo $maxsnaps | $GREP -E '[^[:digit:]]|^0$' > /dev/null 2>&1
    if [ "$?" -eq "0" ]; then
        echo "$progname: \"$maxsnaps\" is not a valid number greater than 0." >&2
        exit 1
    fi    
fi

newsnap=${pool_fs}@${snapname}.$($DATE +%Y%m%d_%H%M)
$ZFS list -t snapshot -H -o name $newsnap >/dev/null 2>&1 
if [ "$?" -eq "0" ]; then
    echo "$progname: Snapshot \"$newsnap\" already exists.  Exiting." >&2
    exit 1
fi   

$ZFS snapshot -r $newsnap
if [ "$?" -ne "0" ]; then
    echo "$progname: Error occurred taking snapshot. Exiting."
    exit 1
fi   
if [ ! -z "$maxsnaps" ]; then
    snapshots=$($ZFS list -r -t snapshot -H -o name -s creation $pool_fs | $GREP "^${pool_fs}@${snapname}\.")
    numsnaps=$(echo $snapshots | $AWK '{ print NF }')
    if [ "$numsnaps" -gt "$maxsnaps" ]; then
        rmsnaps=$((numsnaps - maxsnaps))
        for snapshot in $snapshots; do
            $ZFS destroy -r $snapshot
            if [ "$?" -ne "0" ]; then
                echo "$progname: Error when deleting old snapshot \"$snapshot\". Exiting."
                exit 1;
            fi    
            rmsnaps=$((rmsnaps -= 1))
            if [ "$rmsnaps" -lt "1" ]; then
                break
            fi
        done
     fi   
fi    
exit
# vi: set tabstop=4 shiftwidth=4 si ai nu:
