#!/bin/sh -
#
############################################################################
#
# zfssnap
#
# Usage: zfssnap -s snapname [-n maxsnaps] filesystem
#
# This script takes a snapshot of a ZFS filesystem and all its child
# filesystems.  If a value is specified for "-t" it will also remove the
# oldest snapshots until there are "t" snapshots left (oldest to newest.)
#
# Suggested values for "t": 24 (hourly), 7 (daily), 4 (weekly), 12 (monthly)
#
# Author: Adrian Waters <awaters@draenan.net>
#
############################################################################

defIFS="$(printf " \t\nx")"; defIFS="${IFS%x}"
IFS="$defIFS"

PATH=/bin:/usr/bin

progname=${0##*/}

usage () {
    echo "Usage: $progname -s snapname [-n maxsnaps] filesystem" >&2
    exit 1
}

if [ $( /usr/bin/uname -r | /usr/bin/cut -d. -f1 ) -lt "8" ]; then
    echo "FreeBSD 8.0-RELEASE and above only." >&2
    exit 1
fi
ID=/usr/bin/id
GREP=/usr/bin/grep
ZFS=/sbin/zfs
DATE=/bin/date
AWK=/usr/bin/awk

# Ensure we have the correct number of arguments, and are running as root.

if [ "$#" -lt 3 ]; then
    usage
fi

if [ $($ID -u) -ne "0" ]; then
    echo "You need to be root." >&2
    exit 1
fi

# Gather the arguments.

pool_fs= pool= fs= snapname= maxsnaps=

while getopts :s:n: opt; do
    case $opt in
        s)
            snapname=$OPTARG
            ;;
        n)
            maxsnaps=$OPTARG
            ;;
        '?')
            usage
            ;;
    esac
done

shift $((OPTIND - 1))

# Check that the filesystem name was provided.

if [ -z "$1" ]; then
    usage
fi

# Extract pool (everything before the first '/') and filesystem name
# (everything after it) from the user input.

pool_fs=$1
pool=${pool_fs%%/*}
fs=${pool_fs#*/}
if [ "X$fs" == "X$pool" ]; then
    fs=
fi

# Next few lines sanitizes user input to ensure that the input is in an
# expected format and satisfies the naming conventions for pools and
# filesystems/snapshots. Also checks that the filesystem actually exists.

echo $pool_fs | $GREP -E '^/|/$'
if [ "$?" -eq "0" ]; then
    echo "$progname: Cannot create snapshot: leading or trailing slash in \"$pool_fs\"." >&2
    exit 1
fi

if [ -z "$pool" ]; then
    echo "$progname: Cannot create snapshot: leading slash in \"$pool_fs\"." >&2
    exit 1
fi

echo $pool | $GREP -E '^[[:alpha:]]' | $GREP -Ev '^(c[0-9].*|mirror|raidz|spare|log)$|[^-_.[:alnum:]]' > /dev/null 2>&1
if [ "$?" -eq "1" ]; then
    echo "$progname: \"$pool\" is not a valid ZFS pool name." >&2
    exit 1
fi
if [ ! -z "$fs" ]; then
    echo $fs | $GREP -E '^[[:alnum:]]' | $GREP -Ev '[^-_/.:[:alnum:]]' > /dev/null 2>&1
    if [ "$?" -eq "1" ]; then
        echo "$progname: \"$pool_fs\" is not a valid ZFS filesystem name." >&2
        exit 1
    fi
fi

$ZFS list -H -o name $pool_fs > /dev/null 2>&1

if [ "$?" -ne "0" ]; then
    echo "$progname: ZFS filesystem \"$pool_fs\" does not exist." >&2
    exit 1
fi

echo $snapname | $GREP -E '^[[:alnum:]]' | $GREP -Ev '[^-_.:[:alnum:]]' > /dev/null 2>&1
if [ "$?" -eq "1" ]; then
    echo "$progname: \"$snapname\" is not a valid ZFS snapshot name." >&2
    exit 1
fi

if [ ! -z "$maxsnaps" ]; then
    echo $maxsnaps | $GREP -E '[^[:digit:]]|^0$' > /dev/null 2>&1
    if [ "$?" -eq "0" ]; then
        echo "$progname: \"$maxsnaps\" is not a valid number greater than 0." >&2
        exit 1
    fi
fi

# Generate a new date-based snapshot name and check that a snapshot with
# that name doesn't already exist.

newsnap=${pool_fs}@${snapname}.$($DATE +%Y%m%d_%H%M)
$ZFS list -t snapshot -H -o name $newsnap >/dev/null 2>&1
if [ "$?" -eq "0" ]; then
    echo "$progname: Snapshot \"$newsnap\" already exists.  Exiting." >&2
    exit 1
fi

# Create the snapshot.

$ZFS snapshot -r $newsnap
if [ "$?" -ne "0" ]; then
    echo "$progname: Error occurred taking snapshot. Exiting."
    exit 1
fi

# If "maxsnaps" was specified, generate a list of snapshots from oldest to
# newest, then destroy the oldest snapshot, repeating  until there are
# "maxsnaps" snapshots left.

if [ ! -z "$maxsnaps" ]; then
    snapshots=$($ZFS list -r -t snapshot -H -o name -s creation $pool_fs | $GREP "^${pool_fs}@${snapname}\.")
    numsnaps=$(echo $snapshots | $AWK '{ print NF }')
    if [ "$numsnaps" -gt "$maxsnaps" ]; then
        rmsnaps=$((numsnaps - maxsnaps))
        for snapshot in $snapshots; do
            $ZFS destroy -r $snapshot
            if [ "$?" -ne "0" ]; then
                echo "$progname: Error when deleting old snapshot \"$snapshot\". Exiting."
                exit 1;
            fi
            rmsnaps=$((rmsnaps -= 1))
            if [ "$rmsnaps" -lt "1" ]; then
                break
            fi
        done
     fi
fi
exit
